name: Update Daily Score

on:
  workflow_dispatch:
  schedule:
      - cron:  '0 19 * * *'     # UTC-0 19:00 (UTC+9 - 04:00)

jobs:
  updateDailyScore:
    runs-on: ubuntu-latest
    steps:
  
    # Clone repository
    - uses: actions/checkout@v2
    
    # Setup python 3.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    # Install requirements
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        
    # Run python script
    - name: Run main.py
      run: |
        python main.py
        
    # Commit changes
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: mousedoc
        author_email: sangyun3631@gmail.com
        message: '[Update daily score] - ${{ steps.date.outputs.date }}'
        add: 'export/score-result.txt'
